from . import report_wizard
from . import service_wizard
from . import rep_wizard
from . import product_wizard
from . import voided_wizard
from . import taxes_wizard
from . import best_sellers_wizard
from . import attendance_revenue_wizard
from . import category_wizard
from . import invoice_wizard
from . import returns_wizard
