from . import crm
from . import campaign_type
from . import campaign
from . import campaign_log
from . import channel
from . import contact
from . import contact_note
from . import operator
from . import pos_campaign_ref
from . import res_users
from . import settings
from . import partner